### ISSUE TITLE
bfx-hf-backtest and bfxj-hf-dataserver not compatible.

### ISSUE THREAD

**Issue by ripley** [bitfinexcom/bfx-hf-backtest#3]
In exec_online of backtest, the request is sent as

    // The connection is closed after receiving a 'bt.end' message
    // NOTE: Only the first strategy is used here, as the websocket is shared
    sendWSCommand(btStates[0], 'exec.bt', [
      nFrom,
      nTo,
      symbol,
      tf,
      candles,
      trades,
      candleFields,   <<<<<<
      tradeFields,     <<<<<<
      sync
    ])

However in dataserver's validate_bt_args the msg is parsed as ...

module.exports = (msg = []) => {
  const [
    start, end, symbol, tf, includeCandles, includeTrades, sync
  ] = msg[1] || []

So the sync will get a "*" as value and never pass the validity check.

**Comment by ripley** [comment]
By the way are these bfx-*** projects still maintained? Looks like they've never been touched after being pushed to github.

**Comment by f3rno** [comment]
This has been fixed in `master` some time ago, the issue was never updated. We were in the middle of changing the packet format :)

The projects are definitely still maintained! Most of the work these days is happening at https://gtihub.com/bitfinexcom/bfx-hf-ui
